// Explicit opt-in host test target. Not linked or packaged into Android.
// Reads only bounded P5 gray / P6 RGB fixtures generated by tools/ocr-checks, not image codecs.
#include "ocr_core.h"
#include <cctype>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <unistd.h>
namespace {
void Write(const std::string& text) {
  size_t offset = 0;
  while (offset < text.size()) {
    const auto count = write(STDOUT_FILENO, text.data() + offset, text.size() - offset);
    if (count <= 0) throw tapscene::OcrFailure("OUTPUT_FAILED");
    offset += static_cast<size_t>(count);
  }
}
std::string Token(std::ifstream& input) {
  std::string token;
  char c;
  while (input.get(c)) {
    if (c == '#') { input.ignore(4096, '\n'); continue; }
    if (!std::isspace(static_cast<unsigned char>(c))) { token += c; break; }
  }
  while (input.get(c) && !std::isspace(static_cast<unsigned char>(c))) {
    if (token.size() >= 12) throw tapscene::OcrFailure("INVALID_PGM");
    token += c;
  }
  return token;
}
}
int main(int argc, char** argv) {
  try {
    if (argc == 2 && std::string(argv[1]) == "--version") {
      Write("tapscene-raw-rgb-1 ppocrv6-tiny onnxruntime-1.31.0 opencv-4.14.0\n"); return 0;
    }
    if (argc != 3) return 2;
    std::ifstream input(argv[1], std::ios::binary);
    if (!input) return 2;
    const std::string format = Token(input);
    if (format != "P5" && format != "P6") return 2;
    const int width = std::stoi(Token(input)), height = std::stoi(Token(input));
    if (Token(input) != "255" || width < 1 || height < 1 || width > tapscene::kMaxEdge || height > tapscene::kMaxEdge ||
        static_cast<int64_t>(width) * height > tapscene::kMaxPixels) return 2;
    std::vector<uint8_t> pixels(static_cast<size_t>(width) * height * (format == "P6" ? 3 : 1));
    input.read(reinterpret_cast<char*>(pixels.data()), static_cast<std::streamsize>(pixels.size()));
    if (input.gcount() != static_cast<std::streamsize>(pixels.size()) || input.peek() != std::char_traits<char>::eof()) return 2;
    if (format == "P5") {
      std::vector<uint8_t> rgb(pixels.size() * 3);
      for (size_t i = 0; i < pixels.size(); ++i) rgb[i * 3] = rgb[i * 3 + 1] = rgb[i * 3 + 2] = pixels[i];
      pixels.swap(rgb);
    }
    std::atomic_bool cancel(false);
    const auto result = tapscene::Recognize(pixels.data(), width, height, argv[2], cancel);
    std::ostringstream output;
    output << "level\tpage_num\tblock_num\tpar_num\tline_num\tword_num\tleft\ttop\twidth\theight\tconf\ttext\n";
    int word_number = 0;
    for (const auto& word : result.words) {
      std::string text = word.text;
      for (char& c : text) if (c == '\t' || c == '\r' || c == '\n') c = ' ';
      output << "5\t1\t" << word.block_index + 1 << "\t1\t" << word.line_index + 1 << '\t' << ++word_number << '\t'
             << word.left << '\t' << word.top << '\t' << word.right - word.left << '\t' << word.bottom - word.top << '\t'
             << std::fixed << std::setprecision(6) << word.confidence << '\t' << text << '\n';
    }
    Write(output.str());
    return result.truncated ? 3 : 0;
  } catch (...) { return 2; } // no fixture paths, OCR or exceptions on stderr.
}
